### ISSUE TITLE
possible to support git repo sub-folder?

### ISSUE THREAD

**Issue by jason-xxl** [govend/govend#68]
Hi govend team,

I'm experimenting migrating our repo (100+ deps) to govend from govender. It works fine here except we have some deps are using sub folders with different commit id, for example,

> - path: github.com/stretchr/testify/mock
>   rev: f390dcf405f7b83c997eac1b06768bb9f44dec18
> - path: github.com/stretchr/testify/require
>   rev: e3a8ff8ce36581f87a15341206f205b1da467059

however I noticed govend only supports first level folder, like,

> - path: github.com/stretchr/testify
>   rev: e3a8ff8ce36581f87a15341206f205b1da467059

Have I missed sth? If not support now could we support it in future?

Thanks.

**Comment by tboerger** [comment]
I'm not sure how common this requirement is. I never had requirements like that

**Comment by jason-xxl** [comment]
@tboerger  If I'm right, think of repo like this https://godoc.org/golang.org/x/crypto/*, and I believe its quite common that there're multiple pkgs under same repo. People may just want to vendor one or some of them, not every pkg. Current behaviour is just vendor all including those not used, which is unnecessary.

**Comment by jackspirou** [comment]
Hi @jason-xxl `github.com/stretchr/testify` is a git repo so it has an associated revision hash at its head, but `github.com/stretchr/testify/require` lives within the `.git` directory of `github.com/stretchr/testify` (obvious i know).  I would be surprised if you run into any situations where when attempting to use packages within the same repository they conflict with each other.  If they do i would recommend changing the revision HEAD version of that git repo you are using to a time where they match. 

As for the concern around downloading packages into the `vendor` directory that are "extra" because they are not needed by your project - I totally understand.  While I was developing `govend` for my own needs in different projects this became an issue.  The `prune` flag became a way to prune out those extra packages that are not needed so you don't have to check them into your git repo.  Does the `prune` flag support your needs?

**Comment by jason-xxl** [comment]
Thanks for replies. I'll try if prune could solve my problem first.
